name: Java CI with Maven

on:
  push:
    branches: [ "process" ]
  pull_request:
    branches: [ "process" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean test
      working-directory: milkstore

    - name: Extract Jira Issue Key
      id: extract_jira_key
      run: |
        commit_message=$(git log -1 --pretty=%B)
        echo "Commit message: $commit_message"
        if [[ "$commit_message" =~ ([A-Z0-9]+-[0-9]+) ]]; then
          echo "Found Jira issue key: ${BASH_REMATCH[1]}"
          echo "JIRA_ISSUE_KEY=${BASH_REMATCH[1]}" >> $GITHUB_ENV
        else
          echo "No Jira issue key found in commit message"
          exit 1
        fi

    - name: Create data.json for Jira Update
      run: |
        echo '{ "fields":{ "customfield_10038": {"self": "https://cook-swp.atlassian.net/rest/api/2/customFieldOption/10027", "id" : "10027", "value" : "Pass"} }}' > data.json

    - name: Update Jira
      run: |
        curl -D- -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }} \
        -X PUT --data @data.json -H "Content-Type: application/json" \
        https://cook-swp.atlassian.net/rest/api/2/issue/${{ env.JIRA_ISSUE_KEY }}
